backend:
  name: github
  repo: FrenchyFPS/jekyll-test
  branch: master

publish_mode: editorial_workflow

media_folder: "uploads"

collections:
  - name: "Articles"
    label: "Articles"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Auteur", name: "author", widget: "string"}
      - {label: "Twitter Card", name: "image", widget: "image"}
      - {label: "Texte", name: "body", widget: "markdown"}

  - name: "Page"
    label: "Pages"
    folder: "_pages"
    create: true
    slug: "{{slugg}}"
    fiels: # The fields for each pages
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "thumbnail image", name: "thumbnail image", widget: "image"}
      - {label: "Texte", name: "body", widget: "markdown"}
       
